use gpui::prelude::FluentBuilder;
use gpui::*;
use std::collections::HashMap;
use zqlz_core::{ConnectionFieldSchema, ConnectionFieldType};
use zqlz_ui::widgets::{
    ActiveTheme, Disableable as _, Icon, IconName, IndexPath, WindowExt,
    button::{Button, ButtonVariant, ButtonVariants as _},
    checkbox::Checkbox,
    dialog::DialogButtonProps,
    h_flex,
    input::{Input, InputEvent, InputState},
    select::{Select, SelectEvent, SelectItem, SelectState},
    v_flex,
};

use crate::SavedConnection;

use super::connection_picker::DatabaseType;

#[derive(Clone)]
enum ConnectionFormMode {
    New,
    Edit { saved: SavedConnection },
}

#[derive(Clone, Debug)]
pub enum ConnectionFormEvent {
    Save(SavedConnection),
    Test(SavedConnection),
    Back,
    Cancel,
}

/// Form UI for configuring a selected database connection.
pub struct ConnectionForm {
    mode: ConnectionFormMode,
    database_type: DatabaseType,
    name_input: Entity<InputState>,
    field_inputs: Vec<FieldInput>,
    field_schema: Option<ConnectionFieldSchema>,
    active_tab: String,
    initial_name: String,
    initial_params: HashMap<String, String>,
    name_touched: bool,
    name_autogenerated: bool,
    updating_generated_name: bool,
    submitted: bool,
    test_status: Option<TestConnectionStatus>,
    _subscriptions: Vec<Subscription>,
}

#[derive(Clone, Debug)]
enum TestConnectionStatus {
    Testing,
    Success,
    Error(String),
}

#[derive(Clone)]
struct FieldInput {
    id: String,
    label: String,
    field_type: ConnectionFieldType,
    input: Entity<InputState>,
    select_state: Option<Entity<SelectState<Vec<ConnectionSelectOption>>>>,
    boolean_value: Option<bool>,
    required: bool,
    help_text: Option<String>,
    width: f32,
    row_group: Option<u8>,
    tab: Option<String>,
    touched: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct ConnectionSelectOption {
    value: String,
    label: String,
}

impl SelectItem for ConnectionSelectOption {
    type Value = String;

    fn title(&self) -> SharedString {
        SharedString::from(self.label.clone())
    }

    fn value(&self) -> &Self::Value {
        &self.value
    }
}

impl ConnectionForm {
    pub fn new_for_new(
        database_type: DatabaseType,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Self {
        Self::new(ConnectionFormMode::New, database_type, None, window, cx)
    }

    pub fn new_for_edit(
        database_type: DatabaseType,
        saved: SavedConnection,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Self {
        Self::new(
            ConnectionFormMode::Edit {
                saved: saved.clone(),
            },
            database_type,
            Some(saved),
            window,
            cx,
        )
    }

    fn new(
        mode: ConnectionFormMode,
        database_type: DatabaseType,
        saved: Option<SavedConnection>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Self {
        let name_input = cx.new(|cx| InputState::new(window, cx).placeholder("My Connection"));

        if let Some(saved) = &saved {
            name_input.update(cx, |input, cx| {
                input.set_value(saved.name.clone(), window, cx);
            });
        }

        let (field_schema, field_inputs) =
            Self::build_inputs(&database_type, saved.as_ref(), window, cx);

        let name_autogenerated = matches!(mode, ConnectionFormMode::New);
        if name_autogenerated
            && let Some(name) = Self::generated_name_for(&database_type, &field_inputs, cx)
        {
            name_input.update(cx, |input, cx| {
                input.set_value(name, window, cx);
            });
        }

        let initial_name = name_input.read(cx).text().to_string().trim().to_string();
        let initial_params = Self::field_inputs_params(&field_inputs, cx);

        let mut subscriptions = vec![cx.subscribe_in(
            &name_input,
            window,
            |this, _, event: &InputEvent, window, cx| {
                match event {
                    InputEvent::Change if !this.updating_generated_name => {
                        this.name_touched = true;
                        this.name_autogenerated = false;
                        this.clear_test_status();
                    }
                    InputEvent::Blur => {
                        this.name_touched = true;
                    }
                    InputEvent::PressEnter { .. } => {
                        this.submit(window, cx);
                    }
                    _ => {}
                }
                cx.notify();
            },
        )];

        for field in &field_inputs {
            if !matches!(field.field_type, ConnectionFieldType::Boolean) {
                let field_id = field.id.clone();
                subscriptions.push(cx.subscribe_in(
                    &field.input,
                    window,
                    move |this, _, event: &InputEvent, window, cx| {
                        match event {
                            InputEvent::Change => {
                                this.mark_field_touched(&field_id);
                                this.clear_test_status();
                                this.update_generated_name(window, cx);
                            }
                            InputEvent::Blur => {
                                this.mark_field_touched(&field_id);
                            }
                            InputEvent::PressEnter { .. } => {
                                this.submit(window, cx);
                            }
                            _ => {}
                        }
                        cx.notify();
                    },
                ));
            }

            if let Some(select_state) = &field.select_state {
                subscriptions.push(cx.subscribe(
                    select_state,
                    |this, _, _event: &SelectEvent<Vec<ConnectionSelectOption>>, cx| {
                        this.clear_test_status();
                        cx.notify();
                    },
                ));
            }
        }

        name_input.focus_handle(cx).focus(window, cx);

        Self {
            mode,
            database_type,
            name_input,
            field_inputs,
            field_schema,
            active_tab: "general".to_string(),
            initial_name,
            initial_params,
            name_touched: false,
            name_autogenerated,
            updating_generated_name: false,
            submitted: false,
            test_status: None,
            _subscriptions: subscriptions,
        }
    }

    fn parse_bool(value: &str) -> bool {
        matches!(
            value.trim().to_lowercase().as_str(),
            "true" | "1" | "yes" | "on"
        )
    }

    fn build_inputs(
        database_type: &DatabaseType,
        saved: Option<&SavedConnection>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> (Option<ConnectionFieldSchema>, Vec<FieldInput>) {
        let driver_id = database_type.driver_id();

        let registry = super::connection_picker::driver_registry();
        let Some(driver) = registry.get(driver_id) else {
            tracing::warn!(
                driver_id,
                database_type = database_type.id,
                "No driver schema found for selected database type"
            );
            return (None, Vec::new());
        };

        let mut schema = driver.connection_field_schema();
        if database_type.id == "mariadb" {
            schema.title = std::borrow::Cow::Borrowed("MariaDB Connection");
        }

        let field_inputs = schema
            .fields
            .iter()
            .map(|field| {
                let placeholder = field
                    .placeholder
                    .as_ref()
                    .map(|value| value.to_string())
                    .unwrap_or_default();

                let is_password = matches!(field.field_type, ConnectionFieldType::Password);
                let input = cx.new(|cx| {
                    InputState::new(window, cx)
                        .placeholder(placeholder)
                        .masked(is_password)
                });

                let value = saved
                    .and_then(|saved| saved.params.get(field.id.as_ref()).cloned())
                    .or_else(|| field.default_value.as_ref().map(|value| value.to_string()))
                    .unwrap_or_default();

                if !value.is_empty() {
                    let value_for_input = value.clone();
                    input.update(cx, |input, cx| {
                        input.set_value(value_for_input, window, cx);
                    });
                }

                FieldInput {
                    id: field.id.to_string(),
                    label: field.label.to_string(),
                    field_type: field.field_type.clone(),
                    input,
                    select_state: match &field.field_type {
                        ConnectionFieldType::Select { options } => {
                            let select_options: Vec<ConnectionSelectOption> = options
                                .iter()
                                .map(|option| ConnectionSelectOption {
                                    value: option.value.to_string(),
                                    label: option.label.to_string(),
                                })
                                .collect();

                            let selected_index = if value.is_empty() {
                                None
                            } else {
                                select_options
                                    .iter()
                                    .position(|option| option.value == value)
                                    .map(|index| IndexPath::default().row(index))
                            };

                            Some(cx.new(|cx| {
                                SelectState::new(select_options, selected_index, window, cx)
                            }))
                        }
                        _ => None,
                    },
                    boolean_value: match &field.field_type {
                        ConnectionFieldType::Boolean => Some(Self::parse_bool(&value)),
                        _ => None,
                    },
                    required: field.required,
                    help_text: field.help_text.as_ref().map(|value| value.to_string()),
                    width: field.width,
                    row_group: field.row_group,
                    tab: field.tab.as_ref().map(|value| value.to_string()),
                    touched: false,
                }
            })
            .collect();

        (Some(schema), field_inputs)
    }

    fn get_available_tabs(&self) -> Vec<(String, String)> {
        let mut tabs = vec![("general".to_string(), "General".to_string())];
        let mut seen_tabs = std::collections::HashSet::new();
        seen_tabs.insert("general".to_string());

        for field in &self.field_inputs {
            if let Some(tab) = &field.tab
                && !seen_tabs.contains(tab)
            {
                let label = match tab.as_str() {
                    "ssl" => "SSL",
                    "ssh" => "SSH",
                    "http" => "HTTP",
                    "advanced" => "Advanced",
                    _ => tab.as_str(),
                };
                tabs.push((tab.clone(), label.to_string()));
                seen_tabs.insert(tab.clone());
            }
        }

        tabs
    }

    fn save_connection(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        let saved_connection = self.build_saved_connection(cx);
        cx.emit(ConnectionFormEvent::Save(saved_connection));
    }

    fn build_saved_connection(&self, cx: &App) -> SavedConnection {
        let name = self
            .name_input
            .read(cx)
            .text()
            .to_string()
            .trim()
            .to_string();

        let mut params = HashMap::new();
        for field in &self.field_inputs {
            let value = self.field_value(field, cx);

            if !value.is_empty() {
                params.insert(field.id.clone(), value);
            }
        }

        match &self.mode {
            ConnectionFormMode::New => {
                let mut saved =
                    SavedConnection::new(name.clone(), self.database_type.id.to_string());
                for (key, value) in &params {
                    saved = saved.with_param(key, value);
                }
                saved
            }
            ConnectionFormMode::Edit { saved } => {
                let mut updated = saved.clone();
                updated.name = name;
                updated.params = params;
                updated
            }
        }
    }

    fn name_is_empty(&self, cx: &App) -> bool {
        self.name_input
            .read(cx)
            .text()
            .to_string()
            .trim()
            .is_empty()
    }

    fn field_has_value(&self, field: &FieldInput, cx: &App) -> bool {
        match &field.field_type {
            ConnectionFieldType::Boolean => true,
            ConnectionFieldType::Select { .. } => field
                .select_state
                .as_ref()
                .is_some_and(|state| state.read(cx).selected_value().is_some()),
            _ => !field.input.read(cx).text().to_string().trim().is_empty(),
        }
    }

    fn field_value(&self, field: &FieldInput, cx: &App) -> String {
        Self::field_input_value(field, cx)
    }

    fn field_input_value(field: &FieldInput, cx: &App) -> String {
        match &field.field_type {
            ConnectionFieldType::Select { .. } => field
                .select_state
                .as_ref()
                .and_then(|state| state.read(cx).selected_value().cloned())
                .unwrap_or_default(),
            ConnectionFieldType::Boolean => field.boolean_value.unwrap_or(false).to_string(),
            _ => field.input.read(cx).text().to_string().trim().to_string(),
        }
    }

    fn field_inputs_params(field_inputs: &[FieldInput], cx: &App) -> HashMap<String, String> {
        field_inputs
            .iter()
            .filter_map(|field| {
                let value = Self::field_input_value(field, cx);
                (!value.is_empty()).then(|| (field.id.clone(), value))
            })
            .collect()
    }

    fn number_error(&self, field: &FieldInput, cx: &App) -> Option<&'static str> {
        if !matches!(field.field_type, ConnectionFieldType::Number) {
            return None;
        }

        let value = self.field_value(field, cx);
        if value.is_empty() {
            return None;
        }

        let Ok(number) = value.parse::<u16>() else {
            return Some("Use a whole number");
        };

        if field.id == "port" && number == 0 {
            return Some("Port must be between 1 and 65535");
        }

        None
    }

    fn field_error(&self, field: &FieldInput, cx: &App) -> Option<String> {
        if field.required && !self.field_has_value(field, cx) {
            return Some(format!("{} is required", field.label));
        }

        self.number_error(field, cx).map(str::to_string)
    }

    fn show_field_error(&self, field: &FieldInput, cx: &App) -> Option<String> {
        if self.submitted || field.touched {
            self.field_error(field, cx)
        } else {
            None
        }
    }

    fn missing_required_fields(&self, cx: &App) -> Vec<String> {
        let mut missing = Vec::new();
        if self.name_is_empty(cx) {
            missing.push("Connection Name".to_string());
        }

        missing.extend(
            self.field_inputs
                .iter()
                .filter(|field| field.required && !self.field_has_value(field, cx))
                .map(|field| field.label.clone()),
        );

        missing
    }

    fn invalid_fields(&self, cx: &App) -> Vec<String> {
        self.field_inputs
            .iter()
            .filter(|field| self.number_error(field, cx).is_some())
            .map(|field| field.label.clone())
            .collect()
    }

    fn form_is_valid(&self, cx: &App) -> bool {
        !self.name_is_empty(cx)
            && self
                .field_inputs
                .iter()
                .all(|field| !field.required || self.field_has_value(field, cx))
            && self
                .field_inputs
                .iter()
                .all(|field| self.number_error(field, cx).is_none())
    }

    fn mark_field_touched(&mut self, field_id: &str) {
        if let Some(field) = self
            .field_inputs
            .iter_mut()
            .find(|field| field.id == field_id)
        {
            field.touched = true;
        }
    }

    fn current_params(&self, cx: &App) -> HashMap<String, String> {
        Self::field_inputs_params(&self.field_inputs, cx)
    }

    fn is_dirty(&self, cx: &App) -> bool {
        let name = self
            .name_input
            .read(cx)
            .text()
            .to_string()
            .trim()
            .to_string();

        name != self.initial_name || self.current_params(cx) != self.initial_params
    }

    fn generated_name(&self, cx: &App) -> Option<String> {
        Self::generated_name_for(&self.database_type, &self.field_inputs, cx)
    }

    fn generated_name_for(
        database_type: &DatabaseType,
        field_inputs: &[FieldInput],
        cx: &App,
    ) -> Option<String> {
        let value_for = |id: &str| {
            field_inputs
                .iter()
                .find(|field| field.id == id)
                .map(|field| Self::field_input_value(field, cx))
                .filter(|value| !value.is_empty())
        };

        if (database_type.id == "sqlite" || database_type.id == "duckdb")
            && let Some(path) = value_for("path")
        {
            return std::path::Path::new(&path)
                .file_stem()
                .and_then(|stem| stem.to_str())
                .filter(|stem| !stem.is_empty())
                .map(str::to_string);
        }

        if database_type.id == "turso"
            && let Some(url) = value_for("url")
        {
            return Some(
                url::Url::parse(&url)
                    .ok()
                    .and_then(|url| url.host_str().map(str::to_string))
                    .filter(|host| !host.is_empty())
                    .unwrap_or(url),
            );
        }

        let host = value_for("host")?;
        let database = value_for("database");
        let user = value_for("user").or_else(|| value_for("username"));

        let mut name = user
            .map(|user| format!("{user}@{host}"))
            .unwrap_or_else(|| host.clone());

        if let Some(database) = database {
            name.push('/');
            name.push_str(&database);
        }

        Some(name)
    }

    fn update_generated_name(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        if !self.name_autogenerated {
            return;
        }

        let Some(name) = self.generated_name(cx) else {
            return;
        };

        self.updating_generated_name = true;
        self.name_input.update(cx, |input, cx| {
            input.set_value(name, window, cx);
        });
        self.updating_generated_name = false;
    }

    fn first_invalid_field(&self, cx: &App) -> Option<Option<String>> {
        if self.name_is_empty(cx) {
            return Some(None);
        }

        self.field_inputs
            .iter()
            .find(|field| self.field_error(field, cx).is_some())
            .map(|field| Some(field.id.clone()))
    }

    fn focus_first_invalid(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        match self.first_invalid_field(cx) {
            Some(None) => {
                self.active_tab = "general".to_string();
                self.name_input
                    .update(cx, |input, cx| input.focus(window, cx));
            }
            Some(Some(field_id)) => {
                let target = self
                    .field_inputs
                    .iter()
                    .find(|field| field.id == field_id)
                    .map(|field| {
                        (
                            field.tab.clone().unwrap_or_else(|| "general".to_string()),
                            field.input.clone(),
                            field.select_state.clone(),
                        )
                    });

                if let Some((tab, input, select_state)) = target {
                    self.active_tab = tab;
                    if let Some(select_state) = select_state {
                        select_state.update(cx, |select_state, cx| {
                            select_state.focus(window, cx);
                        });
                    } else {
                        input.update(cx, |input, cx| input.focus(window, cx));
                    }
                }
            }
            None => {}
        }
    }

    fn submit(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        if !self.form_is_valid(cx) {
            self.submitted = true;
            self.focus_first_invalid(window, cx);
            cx.notify();
            return;
        }

        self.save_connection(window, cx);
    }

    fn test_connection(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        if !self.form_is_valid(cx) {
            self.submitted = true;
            self.focus_first_invalid(window, cx);
            cx.notify();
            return;
        }

        let mut saved = self.build_saved_connection(cx);
        saved.id = uuid::Uuid::new_v4();
        self.test_status = Some(TestConnectionStatus::Testing);
        cx.emit(ConnectionFormEvent::Test(saved));
        cx.notify();
    }

    pub fn set_test_result(
        &mut self,
        result: std::result::Result<(), String>,
        cx: &mut Context<Self>,
    ) {
        self.test_status = Some(match result {
            Ok(()) => TestConnectionStatus::Success,
            Err(error) => TestConnectionStatus::Error(error),
        });
        cx.notify();
    }

    fn clear_test_status(&mut self) {
        if !matches!(self.test_status, Some(TestConnectionStatus::Testing)) {
            self.test_status = None;
        }
    }

    fn request_exit(
        &mut self,
        event: ConnectionFormEvent,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        if !self.is_dirty(cx) {
            cx.emit(event);
            return;
        }

        let form = cx.entity().downgrade();
        window.open_dialog(cx, move |dialog, _window, _cx| {
            let event = event.clone();
            let form = form.clone();
            dialog
                .title("Discard Changes?")
                .child("You have unsaved connection changes.")
                .button_props(
                    DialogButtonProps::default()
                        .ok_text("Discard")
                        .ok_variant(ButtonVariant::Danger),
                )
                .on_ok(move |_, _, cx| {
                    if let Err(error) = form.update(cx, |_, cx| cx.emit(event.clone())) {
                        tracing::warn!(?error, "Failed to emit connection form exit event");
                    }
                    true
                })
                .confirm()
        });
    }

    fn render_tabs(&self, tabs: &[(String, String)], cx: &Context<Self>) -> impl IntoElement {
        h_flex()
            .gap_0()
            .border_b_1()
            .border_color(cx.theme().border)
            .children(tabs.iter().map(|(tab_id, tab_label)| {
                let is_active = &self.active_tab == tab_id;
                let tab_id_for_click = tab_id.clone();
                let tab_has_error = self.submitted
                    && self.field_inputs.iter().any(|field| {
                        field.tab.as_deref().unwrap_or("general") == tab_id.as_str()
                            && self.field_error(field, cx).is_some()
                    });

                div()
                    .id(SharedString::from(format!("tab-{}", tab_id)))
                    .px_4()
                    .py_2()
                    .cursor_pointer()
                    .border_b_2()
                    .when(is_active, |this| {
                        this.border_color(cx.theme().accent)
                            .text_color(cx.theme().accent)
                    })
                    .when(!is_active, |this| {
                        this.border_color(gpui::transparent_black())
                            .text_color(cx.theme().muted_foreground)
                    })
                    .hover(|this| {
                        if !is_active {
                            this.text_color(cx.theme().foreground)
                        } else {
                            this
                        }
                    })
                    .on_click(cx.listener(move |this, _, _, cx| {
                        this.active_tab = tab_id_for_click.clone();
                        cx.notify();
                    }))
                    .child(
                        h_flex()
                            .gap_1()
                            .items_center()
                            .text_sm()
                            .font_weight(if is_active {
                                FontWeight::SEMIBOLD
                            } else {
                                FontWeight::NORMAL
                            })
                            .child(tab_label.clone())
                            .when(tab_has_error, |this| {
                                this.child(
                                    div()
                                        .ml_1()
                                        .size(px(6.0))
                                        .rounded_full()
                                        .bg(cx.theme().danger),
                                )
                            }),
                    )
            }))
    }

    fn render_tab_fields(&self, _window: &mut Window, cx: &mut Context<Self>) -> Vec<AnyElement> {
        let fields: Vec<&FieldInput> = self
            .field_inputs
            .iter()
            .filter(|field| match &field.tab {
                Some(tab) => tab == &self.active_tab,
                None => self.active_tab == "general",
            })
            .collect();

        let mut groups: Vec<Vec<&FieldInput>> = Vec::new();
        let mut current_group: Option<u8> = None;
        let mut current_row: Vec<&FieldInput> = Vec::new();

        for field in &fields {
            match (field.row_group, current_group) {
                (Some(group), Some(current)) if group == current => {
                    current_row.push(field);
                }
                (Some(group), _) => {
                    if !current_row.is_empty() {
                        groups.push(current_row);
                    }
                    current_row = vec![field];
                    current_group = Some(group);
                }
                (None, _) => {
                    if !current_row.is_empty() {
                        groups.push(current_row);
                        current_row = Vec::new();
                    }
                    groups.push(vec![field]);
                    current_group = None;
                }
            }
        }

        if !current_row.is_empty() {
            groups.push(current_row);
        }

        groups
            .into_iter()
            .map(|row| {
                if row.len() == 1 {
                    self.render_field(row[0], cx).into_any_element()
                } else {
                    h_flex()
                        .gap_3()
                        .children(row.iter().map(|field| {
                            let element = self.render_field(field, cx);
                            if field.width < 0.5 {
                                div().w(px(100.0)).child(element).into_any_element()
                            } else {
                                div().flex_1().child(element).into_any_element()
                            }
                        }))
                        .into_any_element()
                }
            })
            .collect()
    }

    fn render_field(&self, field: &FieldInput, cx: &mut Context<Self>) -> impl IntoElement {
        let label_element = h_flex()
            .gap_1()
            .child(
                div()
                    .text_sm()
                    .font_weight(FontWeight::MEDIUM)
                    .child(field.label.clone()),
            )
            .when(field.required, |this| {
                this.child(div().text_sm().text_color(cx.theme().danger).child("*"))
            });

        let help_element = field.help_text.as_ref().map(|help| {
            div()
                .text_xs()
                .text_color(cx.theme().muted_foreground)
                .child(help.clone())
        });
        let error_element = self
            .show_field_error(field, cx)
            .map(|error| div().text_xs().text_color(cx.theme().danger).child(error));

        match &field.field_type {
            ConnectionFieldType::FilePath { .. } => {
                let input_for_browse = field.input.clone();

                v_flex()
                    .gap_1()
                    .child(label_element)
                    .child(
                        h_flex()
                            .gap_2()
                            .child(Input::new(&field.input).flex_1())
                            .child(Button::new("browse").label("Browse…").primary().on_click({
                                let input = input_for_browse.clone();
                                cx.listener(move |_, _, window, cx| {
                                    let input = input.clone();
                                    let window_handle = window.window_handle();
                                    let receiver = cx.prompt_for_paths(PathPromptOptions {
                                        files: true,
                                        directories: false,
                                        multiple: false,
                                        prompt: Some("Select File".into()),
                                    });

                                    cx.spawn(async move |_handle, cx| {
                                        if let Ok(Ok(Some(paths))) = receiver.await
                                            && let Some(path) = paths.first()
                                        {
                                            let path_str = path.to_string_lossy().to_string();
                                            if let Err(error) =
                                                window_handle.update(cx, |_, window, cx| {
                                                    input.update(cx, |input, cx| {
                                                        input.set_value(path_str, window, cx);
                                                    });
                                                })
                                            {
                                                tracing::warn!(
                                                    ?error,
                                                    "Failed to update file path field"
                                                );
                                            }
                                        }
                                        Ok::<(), anyhow::Error>(())
                                    })
                                    .detach();
                                })
                            })),
                    )
                    .when_some(error_element, |this, error| this.child(error))
                    .when_some(help_element, |this, help| this.child(help))
            }
            ConnectionFieldType::Select { options } => {
                let placeholder = options
                    .first()
                    .map(|option| option.label.to_string())
                    .unwrap_or_else(|| "Select option".to_string());

                v_flex()
                    .gap_1()
                    .child(label_element)
                    .when_some(field.select_state.as_ref(), |this, select_state| {
                        this.child(Select::new(select_state).placeholder(placeholder))
                    })
                    .when_some(error_element, |this, error| this.child(error))
                    .when_some(help_element, |this, help| this.child(help))
            }
            ConnectionFieldType::Boolean => {
                let checked = field.boolean_value.unwrap_or(false);
                let field_id = field.id.clone();

                v_flex()
                    .gap_1()
                    .child(label_element)
                    .child(
                        Checkbox::new(SharedString::from(format!("connection-field-{}", field.id)))
                            .checked(checked)
                            .on_click(cx.listener(move |this, new_checked, _window, cx| {
                                if let Some(field) = this
                                    .field_inputs
                                    .iter_mut()
                                    .find(|field| field.id == field_id)
                                {
                                    field.boolean_value = Some(*new_checked);
                                    this.clear_test_status();
                                    cx.notify();
                                }
                            })),
                    )
                    .when_some(error_element, |this, error| this.child(error))
                    .when_some(help_element, |this, help| this.child(help))
            }
            ConnectionFieldType::Number => v_flex()
                .gap_1()
                .child(label_element)
                .child(Input::new(&field.input))
                .when_some(error_element, |this, error| this.child(error))
                .when_some(help_element, |this, help| this.child(help)),
            ConnectionFieldType::Password => v_flex()
                .gap_1()
                .child(label_element)
                .child(Input::new(&field.input).mask_toggle())
                .when_some(error_element, |this, error| this.child(error))
                .when_some(help_element, |this, help| this.child(help)),
            ConnectionFieldType::Text => v_flex()
                .gap_1()
                .child(label_element)
                .child(Input::new(&field.input))
                .when_some(error_element, |this, error| this.child(error))
                .when_some(help_element, |this, help| this.child(help)),
        }
    }
}

impl Render for ConnectionForm {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let is_edit_mode = matches!(self.mode, ConnectionFormMode::Edit { .. });

        let title = if is_edit_mode {
            self.field_schema
                .as_ref()
                .map(|schema| schema.title.to_string().replace("New", "Edit"))
                .unwrap_or_else(|| format!("Edit {} Connection", self.database_type.name))
        } else {
            self.field_schema
                .as_ref()
                .map(|schema| schema.title.to_string())
                .unwrap_or_else(|| format!("New {} Connection", self.database_type.name))
        };

        let action_button_label = if is_edit_mode {
            "Save Connection"
        } else {
            "Create Connection"
        };

        let tabs = self.get_available_tabs();
        let has_tabs = tabs.len() > 1;
        let has_schema = self.field_schema.is_some();
        let name_is_empty = self.name_is_empty(cx);
        let form_is_valid = self.form_is_valid(cx);
        let test_is_running = matches!(self.test_status, Some(TestConnectionStatus::Testing));
        let show_name_error = name_is_empty && (self.submitted || self.name_touched);
        let missing_fields = self.missing_required_fields(cx);
        let invalid_fields = self.invalid_fields(cx);
        let (footer_message, footer_color) = if let Some(test_status) = &self.test_status {
            match test_status {
                TestConnectionStatus::Testing => (Some("Testing connection...".to_string()), None),
                TestConnectionStatus::Success => (
                    Some("Connection test passed".to_string()),
                    Some(cx.theme().success),
                ),
                TestConnectionStatus::Error(error) => (
                    Some(format!("Connection test failed: {error}")),
                    Some(cx.theme().danger),
                ),
            }
        } else if !missing_fields.is_empty() {
            (
                Some(format!("Required: {}", missing_fields.join(", "))),
                None,
            )
        } else if !invalid_fields.is_empty() {
            (Some(format!("Fix: {}", invalid_fields.join(", "))), None)
        } else {
            (None, None)
        };

        v_flex()
            .size_full()
            .p_4()
            .gap_4()
            .child(
                h_flex()
                    .gap_3()
                    .items_center()
                    .when(!is_edit_mode, |this| {
                        this.child(
                            Button::new("back")
                                .icon(Icon::new(IconName::ArrowLeft).size_4())
                                .ghost()
                                .on_click(cx.listener(|this, _, window, cx| {
                                    this.request_exit(ConnectionFormEvent::Back, window, cx);
                                })),
                        )
                    })
                    .child(self.database_type.logo.medium())
                    .child(
                        div()
                            .text_lg()
                            .font_weight(FontWeight::SEMIBOLD)
                            .child(title),
                    ),
            )
            .when(has_tabs, |this| this.child(self.render_tabs(&tabs, cx)))
            .child(
                div()
                    .id("connection-form-content")
                    .flex_1()
                    .overflow_y_scroll()
                    .child(
                        v_flex()
                            .gap_4()
                            .p_2()
                            .when(!has_schema, |this| {
                                this.child(
                                    div()
                                        .text_sm()
                                        .text_color(cx.theme().muted_foreground)
                                        .child("Connection schema is unavailable for this driver."),
                                )
                            })
                            .when(self.active_tab == "general", |this| {
                                this.child(
                                    v_flex()
                                        .gap_1()
                                        .child(
                                            h_flex()
                                                .gap_1()
                                                .child(
                                                    div()
                                                        .text_sm()
                                                        .font_weight(FontWeight::MEDIUM)
                                                        .child("Connection Name"),
                                                )
                                                .child(
                                                    div()
                                                        .text_sm()
                                                        .text_color(cx.theme().danger)
                                                        .child("*"),
                                                ),
                                        )
                                        .child(Input::new(&self.name_input))
                                        .when(show_name_error, |this| {
                                            this.child(
                                                div()
                                                    .text_xs()
                                                    .text_color(cx.theme().danger)
                                                    .child("Connection name is mandatory"),
                                            )
                                        }),
                                )
                            })
                            .children(self.render_tab_fields(window, cx)),
                    ),
            )
            .child(
                v_flex()
                    .gap_2()
                    .pt_2()
                    .border_t_1()
                    .border_color(cx.theme().border)
                    .child(
                        h_flex()
                            .justify_end()
                            .gap_2()
                            .child(
                                Button::new("test")
                                    .label("Test Connection")
                                    .secondary()
                                    .disabled(!form_is_valid || test_is_running)
                                    .on_click(cx.listener(|this, _, window, cx| {
                                        this.test_connection(window, cx);
                                    })),
                            )
                            .child(Button::new("cancel").label("Cancel").ghost().on_click(
                                cx.listener(|this, _, window, cx| {
                                    this.request_exit(ConnectionFormEvent::Cancel, window, cx);
                                }),
                            ))
                            .child(
                                Button::new("save")
                                    .label(action_button_label)
                                    .primary()
                                    .disabled(!form_is_valid)
                                    .on_click(cx.listener(|this, _, window, cx| {
                                        this.submit(window, cx);
                                    })),
                            ),
                    )
                    .when_some(footer_message, |this, message| {
                        this.child(
                            div()
                                .w_full()
                                .text_xs()
                                .whitespace_normal()
                                .text_color(cx.theme().muted_foreground)
                                .when_some(footer_color, |this, color| this.text_color(color))
                                .child(message),
                        )
                    }),
            )
    }
}

impl EventEmitter<ConnectionFormEvent> for ConnectionForm {}
